import { Enum } from './enum.js';

const TokenTypes = Enum(
  `NUMBER, IDENTIFIER, STRING, LET, NIL,
	
	SEMICOLON, ARROW, COMMA, DOT, COLON,

	EQUAL_EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL,

	BITWISE_AND, BITWISE_OR, BITWISE_LSHIFT, BITWISE_RSHIFT,

	AND, OR,
	
	PLUS, MINUS, MUL, DIV, POW, ASSIGN,

	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,

	FUN, CLASS, EXTENDS, RETURN, IF, ELSE, WHILE, BREAK, CONTINUE, FOR`,
);

export { TokenTypes };
